### ISSUE TITLE
FTBS w/ Python 3.13 - implicit declaration of function ‘PyEval_InitThreads’, 'PyEval_CallObject'

### ISSUE THREAD

**Issue by knight-of-ni** [Pulse-Eight/libcec#645]
libcec fails to build with Python 3.13.0a1.

/builddir/build/BUILD/libcec-libcec-6.0.2/redhat-linux-build/src/libcec/CMakeFiles/_cec.dir/libcecPYTHON_wrap.cxx:5497:9: error: ‘PyEval_InitThreads’ was not declared in this scope; did you mean ‘PyEval_SaveThread’?
 5497 |         PyEval_InitThreads();
      |         ^~~~~~~~~~~~~~~~~~
      |         PyEval_SaveThread

/builddir/build/BUILD/libcec-libcec-6.0.2/src/libcec/SwigHelper.h:122:18: error: â€˜PyEval_CallObjectâ€™ was not declared in this scope; did you mean â€˜PyObject_CallObjectâ€™?
  122 |         result = PyEval_CallObject(m_callbacks[callback], arglist);
      |                  ^~~~~~~~~~~~~~~~~
      |                  PyObject_CallObject

More details can be found here:
https://bugzilla.redhat.com/show_bug.cgi?id=2245791

The fix looks fairly straightforward. If needed I can provide a PR to resolve this, after I return from an out of town trip for day job.

**Comment by opdenkamp** [comment]
this has been fixed in libCEC 7.0.0
