### ISSUE TITLE
Python Binding - Ubuntu not working

### ISSUE THREAD

**Issue by Lcpuche** [Pulse-Eight/libcec#450]
Hello,

I followed all the steps and got it working in a RASPBERRY PI with no issues. However, trying to follow the Linux-based instructions yields this error when running under Python3 and Python2:

```
  File "/media/sf_shared/Transferer/pyCecClient.py", line 39, in pyCecClient
    cecconfig = cec.libcec_configuration()
AttributeError: module 'cec' has no attribute 'libcec_configuration'
```

Anyone know how to resolve this?

Additionally, before compiling and installing, command line functioned. (With the sudo apt-get install cec-utils). However now, it only returns 'autodetect FAILED'.

**Comment by neilmunday** [comment]
I have the same issue under Arch Linux on the Raspberry Pi using Python 2.7.

**Comment by neilmunday** [comment]
If it helps, it works fine if you checkout tag libcec-4.0.0.

**Comment by neilmunday** [comment]
Just to add, under Fedora 27 (x86_64) the Python bindings work fine with Python 3 but not Python 2.7.

Steps to reproduce:

```
git clone https://github.com/Pulse-Eight/libcec
cd libcec
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/home/neil/test -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib64/libpython2.7.so ..
make -j
make install
```
Now try importing and using the module:

```
export PYTHONPATH=/home/neil/test/lib/python2.7/site-packages
$ python2
Python 2.7.15 (default, Oct 15 2018, 18:36:25) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cec
>>> cec.libcec_configuration()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'libcec_configuration'
>>>
```

**Comment by opdenkamp** [comment]
closing this one because it's been fixed already
